### PR TITLE
When ThrowIfNull is true, an exception is now thrown only if both the key with the classname and the key w/o it are missing from the config file

### PR DESCRIPTION
**Pull request by urig**
Hi @ChrisMissal , 

This PR resolves issue https://github.com/ChrisMissal/Formo/issues/43 .  
I recommend ignoring whitespace using [?w=1](https://github.com/blog/967-github-secrets) because VS felt line endings were inconsistent in one of the files :)
Please hold no punches when reviewing - Would love to learn and improve my PR-fu.

Thanks,
Uri

### CODE REVIEW

**Comment by urig** [comment]
Hi @ChrisMissal, I'm sure you're very busy and I don't mean to be pushy but - ping? :)

**Comment by ChrisMissal** [comment]
Thanks for the reminder! I'm checking it out now.

**Comment by ChrisMissal** [comment]
@urig It feels like we're using Exceptions as control flow in the new GetValueOrNull method. Can we tackle this another way? I'm not saying I won't merge, but I wanted to see if you had other thoughts when working on this?

**Comment by urig** [comment]
Many thanks for the feedback Chris. 

I've just taken some time to look at `GetValueOrNull()`. To avoid relying on exception throwing for control flow, I thought it would be straightforward to replace the call to 'configuration.ConnectionString.Get(key)' with a call to a "TryGet" method. 

But it seems to me that this is going to be quite complicated as the only (?) option is to call `ConnectionStringsConfiguration.TryGetMember()`. That method's first parameter is of the abstract type `GetMemberBinder` and, to be frank, I don't know of a simple way of getting from `string key` to an instance of that.

If you know of a simpler approach, I'd love to learn and implement it. If not, then IMHO the current implementation is the lesser evil. :)

**Comment by ChrisMissal** [comment]
That's kind of where I landed as well, I just wanted to see what your thoughts were. The only final (tiny) thing I think I'd like is moving those new InvalidOperationExceptions into the ThrowHelper class so the message isn't repeated.

**Comment by urig** [comment]
Done. :)

**Comment by ChrisMissal** [comment]
Sorry @urig, life is beautiful chaos :)

I'll try to get a new NuGet out later tonight!

**Comment by urig** [comment]
Many thanks - much appreciated. Take your time, there's no rush :)

**Comment by ChrisMissal** [comment]
New NuGet package is released @urig - https://www.nuget.org/packages/Formo

**Comment by urig** [comment]
Thanks Chris, you're the best :)

**Pull request merged**
