### PR TITLE
Added ability to pass in a precreated object to the Bind method

### PR DESCRIPTION
**Pull request by tompipe**

### CODE REVIEW

**Comment by ChrisMissal** [comment]
Thanks @tompipe! I see no reason this won't get merged in, but I want to play around with it before I do. Stay tuned please :smile:

**Comment by tompipe** [comment]
I'm using it already on a site and it works flawlessly. 

Great work with this btw, its really handy

**Comment by ChrisMissal** [comment]
@tompipe your addition is now in Nuget btw: https://www.nuget.org/packages/Formo/

**Comment by tompipe** [comment]
Awesome! Thanks

**Pull request merged**
